### ISSUE TITLE
คำถาม: คำพูดจากเว็บ ควรใช้คำบ่งเพศ (เช่น ครับ/ค่ะ) หรือไม่?

### ISSUE THREAD

**Issue by neizod** [jittat/admapp#14]
เมื่อเปิดหน้าแรกขึ้นมา จะเจอข้อความเช่นนี้

    สวัสดีครับ
    เข้าใช้ระบบรับสมัคร
    รหัสประจำตัวประชาชนหรือหมายเลขพาสปอร์ต*

สังเกตว่ามีการใช้คำว่า "ครับ" คำถามคือเราสามารถใช้คำบ่งเพศเช่นนี้ได้หรือไม่?

**Comment by jittat** [comment]
ข้อความแก้ทีหลังได้ครับ ทำส่วนอื่นให้เสร็จก่อนครับ
