### ISSUE TITLE
เพิ่ม eligibility hook ของโครงการรับสมัครกับผู้สมัคร

### ISSUE THREAD

**Issue by jittat** [jittat/admapp#22]
- [x] ตั้งค่าแต่ละโครงการ
  - [x] ช้างเผือก -- 400 โรงเรียนแรก
- [x] ตัวแปร
  - [x] ตัวแปรสมัครได้หรือไม่
  - [x] ตัวแปรซ่อนหรือไม่
  - [x] ตัวแปรข้อความเพิ่มเติม
- [x] การแสดงผล
  - [x] แสดงโครงการที่สมัครไม่ได้ แต่ไม่สามารถคลิกเข้าไปได้
  - [x] ไม่แสดงโครงการที่ซ่อน
  - [x] แสดงข้อความเพิ่มเติม

**Comment by neizod** [comment]
spec:
- ตอบ 3 คำถาม:
  - สมัครได้หรือไม่?
  - ซ่อนหรือไม่?
  - ข้อความเพิ่มเติม

implement idea:
- ที่ view index หาโครงการทั้งหมดที่ผู้สมัครแต่ละคนเห็น แล้ว hook ตัวแปรเหล่านี้เข้าไป
