### ISSUE TITLE
ตรวจสอบ GPA ในหน้าประวัติการศึกษา

### ISSUE THREAD

**Issue by srakrn** [jittat/admapp#31]
https://admission.ku.ac.th/adm61test/appl/education/

ตรวจสอบว่า GPA นั้นเป็น GPA ที่ถูกต้อง (อยู่ระหว่าง 0.00 - 4.00)

![screenshot from 2017-10-09 12-46-06](https://user-images.githubusercontent.com/3682634/31326279-eff07ce0-acef-11e7-9ad7-a0af87eaf742.png)

**Comment by neizod** [comment]
ใช้ regex ตรวจไปนะครับ (`^[0-3]\.[0-9]{2}|4\.00$`) น่าจะไม่พลาดแหละแต่ลองจิ้มๆ ดูก็ดีว่ามีหลุดหรือเปล่า

อ๋อ ผมบังคับใส่เลขพร้อมจุดทศนิยมสองตำแหน่งนะ ดังนั้นใส่ `3.50` มาได้ แต่ใส่ `3.5` เฉยๆ ไม่ได้

**Comment by neizod** [comment]
regex ตรวจค่าใช้งานได้ดีไม่มีปัญหาครับ แต่คำพูดเวลา error มันไม่พ่นออกมาด้วย เดี๋ยวหาทางแก้แปปครับ

**Comment by neizod** [comment]
ยังเหลือปัญหาอยู่หน่อยนึงครับ (คิดว่าไม่สำคัญเท่าไหร่) คือตอนนี้เก็บเป็น float แล้วอาจจะใส่เลขยาวๆ เช่น `3.1415926` ได้ ไม่แน่ใจว่าต้อง trim ให้เหลือทศนิยมแค่ 2 ตำแหน่งหรือเปล่า?
