### ISSUE TITLE
ฟอร์มโครงการทีมชาติไม่สามารถกดยกเลิกได้

### ISSUE THREAD

**Issue by srakrn** [jittat/admapp#45]
![screenshot from 2017-10-09 17-23-23](https://user-images.githubusercontent.com/3682634/31334023-91dc9748-ad16-11e7-936b-3adc04017044.png)

Replication steps:
1) สมัครโครงการนักกีฬา
2) กดยกเลิกโดยไม่ต้องกรอกข้อมูลใดๆ

**Comment by neizod** [comment]
กำลังคิดอยู่ว่าปุ่ม "ยกเลิก" นี่ไม่จำเป็นสำหรับ UI เว็บในปัจจุบันหรือเปล่าครับ? คือเดี๋ยวนี้ถ้าจะยกเลิกก็กด back ย้อนกลับหน้าเดิมไปเลย
