### ISSUE TITLE
ปุ่ม "ขณะนี้" ในหน้าแอดมินทำงานได้ไม่ถูกต้อง

### ISSUE THREAD

**Issue by srakrn** [jittat/admapp#49]
https://admission.ku.ac.th/admin/appl/admissionprojectround/add/

![screenshot from 2017-10-09 22-31-44](https://user-images.githubusercontent.com/3682634/31345990-b94ba5c8-ad41-11e7-8f32-c8ab1d7c89d9.png)

ปุ่ม "ขณะนี้" เมื่อกดจะทำการเติมเวลาที่มีคำว่า "undefined" พ่วงต่อท้าย ทำให้ไม่สามารถบันทึกเวลาได้

**Comment by jittat** [comment]
เป็นที่ django ครับ ขออนุญาตปิดครับ
