### ISSUE TITLE
ปรับ style ของ error message ในฟอร์ม registration

### ISSUE THREAD

**Issue by jittat** [jittat/admapp#5]

**Comment by Bell001** [comment]
ปรับ style โดยอ้างอิง เป็น p.class_help-block ใน base.css แล้วนะคะ

**Comment by jittat** [comment]
ขอบคุณมากครับ ผมเอาไปแก้ต่ออีกหน่อยดังนี้นะครับ

* ผมเอาลิงก์ bootstrap 4-alpha ที่ใส่เพิ่มมาออกแล้วนะครับ (เราใช้ bootstrap 4-beta)
* ของเก่า error ที่คุณทำมา มันต้องใช้ bootstrap alpha เพราะว่า crispy form มันเป็นเวอร์ชั่นเก่า ทำให้มันใส่ class ผิดพลาด
* ผมเลยไปเอา crispy form อันล่าสุดมาลง ตอนนี้แสดงได้แล้ว
* แต่ต้องแก้คลาสจะเป็น p.invalid-feedback แทนครับ

**Comment by Bell001** [comment]
รับทราบค่ะ ขอบคุณค่าอาจารย์

2017-09-26 14:10 GMT+07:00 Jittat Fakcharoenphol <notifications@github.com>:
