### ISSUE TITLE
ฟอร์มไม่ซ่อนเป็นมาตรฐาน

### ISSUE THREAD

**Issue by srakrn** [jittat/admapp#55]
เอกสารเพิ่มเติมประกอบการสมัคร และ หลักฐานการเปลี่ยนชื่อหรือชื่อสกุล หน้ารับสมัครของโครงการช้างเผือก ไม่ซ่อนเป็นค่า default

https://admission.ku.ac.th/kuadm/appl/

![screenshot from 2017-10-10 09-09-50](https://user-images.githubusercontent.com/3682634/31366529-ab0d412e-ad9b-11e7-9071-1b053124eeae.png)

**Comment by srakrn** [comment]
(เอ๊ะ อันนี้หรือว่าเพราะผมอัพโหลดเอกสารทั้งสามแล้ว มันเลยซ่อนไว้ให้ครับ?)

**Comment by monthol8th** [comment]
เดี๋ยวจะดูให้ครับ

**Comment by srakrn** [comment]
ถ้าแบบนั้นพฤติกรรมถูกต้องแล้ว ขอ close เลยนะครับ
